// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcTuMoNknmpAE57rNjsmmTx3itsKthOVM',
    appId: '1:940921448646:web:ba59df4e9ec3e2c7700fc7',
    messagingSenderId: '940921448646',
    projectId: 'ze-connect-v2-dev',
    authDomain: 'ze-connect-v2-dev.firebaseapp.com',
    storageBucket: 'ze-connect-v2-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4hPtIcwevHv6fXkXbvrzAljeBmfpGPCA',
    appId: '1:940921448646:android:b818f9ae71248334700fc7',
    messagingSenderId: '940921448646',
    projectId: 'ze-connect-v2-dev',
    storageBucket: 'ze-connect-v2-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-iQF2vMTEPfCkhb3pMAkgMNjsl3XkEo',
    appId: '1:940921448646:ios:5fbf3b0b241876f4700fc7',
    messagingSenderId: '940921448646',
    projectId: 'ze-connect-v2-dev',
    storageBucket: 'ze-connect-v2-dev.firebasestorage.app',
    iosBundleId: 'com.example.zeConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-iQF2vMTEPfCkhb3pMAkgMNjsl3XkEo',
    appId: '1:940921448646:ios:5fbf3b0b241876f4700fc7',
    messagingSenderId: '940921448646',
    projectId: 'ze-connect-v2-dev',
    storageBucket: 'ze-connect-v2-dev.firebasestorage.app',
    iosBundleId: 'com.example.zeConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcTuMoNknmpAE57rNjsmmTx3itsKthOVM',
    appId: '1:940921448646:web:3347e49a531c8e30700fc7',
    messagingSenderId: '940921448646',
    projectId: 'ze-connect-v2-dev',
    authDomain: 'ze-connect-v2-dev.firebaseapp.com',
    storageBucket: 'ze-connect-v2-dev.firebasestorage.app',
  );
}
